# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Place.delete_all

[
  {:title => "John Hancock Center", :photo_url => "http://www.johnhancockcenterchicago.com/images/photo_building.jpg", :price => 2000, :description => "From the official website: Since its completion in 1970, JOHN HANCOCK CENTER stands as the pre-eminent address for local, national and international business. With its significant architecture, solid steel foundation and captivating views of four states, JOHN HANCOCK CENTER's iconic presence in Chicago's skyline serves to amplify the profiles of the diverse and important businesses within its fold. Nowhere but JOHN HANCOCK CENTER has such a distinguished address."},
  {:title => "Shedd Aquarium", :photo_url => "http://www.destination360.com/north-america/us/illinois/images/s/illinois-shedd-aquarium.jpg", :price => 3595, :description => "From the official website: Shedd combines the best of early 20th-century \"age of aquariums\" characteristics—a diverse, global animal collection surrounded by eye-popping architecture—with 21st-century advances in animal care, environments and interpretation. Excellence and innovation are Shedd traditions, and they began with the founder."},
  {:title => "Big and Little's", :photo_url => "http://chicago.seriouseats.com/images/2012/10/20121005-225144-tgi-fry-day-big-littles.jpg", :price => 895, :description => "From Zagat: \"Unbelievably good\" tacos, \"out-of-this-world\" po' boys and fish 'n' chips that'll \"blow you away\" are what it's about at these seafood-centric counter-serves where favorites like burgers and hot dogs provide \"enough non-fish options\" to make \"everyone happy\"; they're cash-only, get \"crowded\" at prime times and have \"no atmosphere\" to speak of, but with \"huge\" portions and \"reasonable\" tabs, you really \"can't go wrong.\""},
  {:title => "Cloud Gate", :photo_url => "http://static1.squarespace.com/static/50f07ce8e4b07454d6dd2f2f/510c40c1e4b0329f42470010/510c414be4b08a64f471555b/1428686840037/atwood.jpg?format=300w", :price => "2995", :description => "From the official website: The Adler Planetarium — America's First Planetarium — was founded in 1930 by Chicago business leader Max Adler. The museum is home to three full-size theaters, extensive space science exhibitions, and one of the world's most important antique astronomical instrument collections on display. The Adler is a recognized leader in science education, with a focus on inspiring young people, particularly women and minorities, to pursue careers in science."},
  {:title => "United Center", :photo_url => "http://hockey.ballparks.com/NHL/ChicagoBlackhawks/interior.jpg", :price => 20000, :description => "From the official website: In 1988, William Wirtz, owner of the Chicago Blackhawks, and Jerry Reinsdorf, majority owner and Team Chairman of the Chicago Bulls, formed a new partnership to create an arena that would take sports and entertainment into the 21st century. The United Center, home to the Chicago Blackhawks and Chicago Bulls, is the largest arena in the United States. Construction was begun in April of 1992, with the ribbon cutting ceremony being held on August 18, 1994. Since opening, the United Center has hosted over 200 events each year. Some of the events the United Center has been proud to host include the 1996 Democratic National Convention, The Rolling Stones, Eric Clapton, Bruce Springsteen and the E Street Band, Paul McCartney, U2, The Who, The 3 Tenors, Ringling Brothers and Barnum & Bailey Circus, Disney on Ice, the Big Ten Men's Basketball Tournament, the Men's NCAA Basketball Tournament, the Great Eight Classic, Illinois College Basketball, and Champions on Ice. The United Center has hosted over forty million guests since its opening in 1994."},
  {:title => "Young Memorial Building", :photo_url => "http://storage.lib.uchicago.edu/ucpa/series2/derivatives_series2/apf2-08921t.gif", :price => 500000, :description => "From the University of Chicago archives: The University of Chicago acquired the Young Memorial Building in 1963. It has functioned as departmental space for the university's architect, security, housing, and administrative facilities. It was originally part of the Chicago Home for Incurables."},
  {:title => "Jimmy's (Woodlawn Tap)", :photo_url => "http://www.chibarproject.com/Reviews/WoodlawnTap/WoodlawnTapStreetShotSP.JPG", :price => 300, :description => "From the Chicago Bar Project: The Woodlawn Tap, better known simply as \"Jimmy's\" because of the legendary barkeep that owned it for a half century, busily caters to students, professors and even Nobel Peace prize winners from the University of Chicago with equal vigor as to neighborhood residents, tradesmen and barstool philosophers from the School of Hard Knocks, of all races and economic solvencies. Even the inebriate poet, Dylan Thomas, is said to have whet his whistle on three separate occasions at the Woodlawn Tap (on the same day). Back then, this strip of 55th was a bustling strip of boozing until the urban decay set in that plagued the city from the time of the riots, following the assassination of Martin Luther King Jr. in 1968, all the way through the mid-1980s. A good bar is hard to find in these parts today, though The Cove and Bar Louie tries hard and both Seven Ten and the New Checkerboard Lounge have moved in. Jimmy's Woodlawn Tap is still the place to go in Hyde Park for conversation, cheap-but-good pub grub and free jazz every Sunday night, even though Jimmy has since gone to tend that Great Tavern in the Sky."}
].each do |place_hash|
  Place.create! place_hash
end