source 'https://rubygems.org'

gem 'rails', '~> 4.2.0'
gem 'sqlite3'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'

gem 'quiet_assets'
gem 'simple_form'
# used the command: rails g scaffold places

source 'https://rails-assets.org' do
  gem 'rails-assets-ion.rangeSlider'
  gem 'rails-assets-jquery'
  gem 'rails-assets-jquery-ujs'
  gem 'rails-assets-jquery-ui'
  gem 'rails-assets-bootstrap'
  gem 'rails-assets-bootstrap-ui'
  gem 'rails-assets-fontawesome'

end